"""Add is_manually_reviewed to Document

Revision ID: 21de2a3aa84a
Revises: daf4667480af
Create Date: 2026-07-13 13:32:49.174234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21de2a3aa84a'
down_revision: Union[str, Sequence[str], None] = 'daf4667480af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('is_manually_reviewed', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'is_manually_reviewed')
    # ### end Alembic commands ###
