"""add claim owner, completeness score, document confidence

Revision ID: 94928c16cf49
Revises: b80d24120d87
Create Date: 2026-07-13 10:50:07.448474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94928c16cf49'
down_revision: Union[str, Sequence[str], None] = 'b80d24120d87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('claims', sa.Column('completeness_score', sa.Float(), nullable=True))
    op.alter_column('claims', 'creation_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'claims', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('documents', sa.Column('classification_confidence', sa.Float(), nullable=True))
    op.drop_column('documents', 'extracted_fields')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('extracted_fields', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('documents', 'classification_confidence')
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.alter_column('claims', 'creation_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('claims', 'completeness_score')
    op.drop_column('claims', 'user_id')
    # ### end Alembic commands ###
