"""add claim_type to claims

Revision ID: daf4667480af
Revises: 94928c16cf49
Create Date: 2026-07-13 12:43:35.631289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daf4667480af'
down_revision: Union[str, Sequence[str], None] = '94928c16cf49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('claim_type', sa.String(length=20), server_default='auto', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claims', 'claim_type')
    # ### end Alembic commands ###
